### ISSUE TITLE
[BUG] Project varients missing settings

### ISSUE THREAD

**Issue by Chief-T1** [evershopcommerce/evershop#531] opened 2024-05-13 09:15 UTC
**Describe the bug**
The version 1.1.0 release does not show product varients under the products page. 

This means that settings for product varients for example manage stock / stock availability can't be easily changed from the UI. 

Some settings can be changed by clicking on the main product and then scrolling to varients. You can then change the number of items in stock, status and visibility. 

**To Reproduce**
1. Go to 'Admin'
2. Click on 'Products'
3. Product varients are missing

**Expected behavior**

I expect to be able to access and manage all the product varient settings. 

**Screenshots**

**Background (please complete the following information):**
 - NodeJS Version
 - Postgres Version
 - EverShop Version: 1.1.0
 - OS: [e.g. Window, Ubuntu, Mac-OS]
 - Browser [e.g. Chrome, Safari]

**Additional context**

**Comment by treoden** [comment] 2024-05-13 10:18
Hi @Chief-T1 ,

Yes that is one of the change we shipped in v1.1.0. 
The reason is many users don't want to see so many item of the same variant group on the list. Some of the variant group have so many variant and it push another product/variant to another page. So from now we will only display 1 variant per group. You can still access to all variant by clicking on that item and see the variant list from the bottom of the page. From here you can click to any item and see/modify the detail information for each of them

Thanks

**Comment by Chief-T1** [comment] 2024-05-14 18:25
Hi @treoden 

Thanks for explaining why variants have been removed from the product list, I can see how only showing one variant would be better. 
I still think there is a bug when viewing the variants as the inventory settings are missing: 
![image](https://github.com/evershopcommerce/evershop/assets/75487499/0ab03ca2-34c7-43fd-9bea-60144050d975)

On a product page, you have these options: 
![image](https://github.com/evershopcommerce/evershop/assets/75487499/0f0eb3c5-8c82-4ae7-ae93-2cd24449a966)

**Comment by Chief-T1** [comment] 2024-05-14 18:35
I just realised you can click on the SKU to access the variant page with all the detailed settings. Sorry I didn't realise this was possible: 
![image](https://github.com/evershopcommerce/evershop/assets/75487499/458250df-fc5b-4295-bb61-f44c61b600f0)

**Comment by treoden** [comment] 2024-05-15 02:12
I assume the issue is settled. Closing the ticket
Thanks

**Closed by treoden** 2024-05-15 02:12 UTC
