### ISSUE TITLE
[BUG] Default Copyright text is not visible

### ISSUE THREAD

**Issue by dev-ST-IA** [evershopcommerce/evershop#366] opened 2023-10-14 11:16 UTC
Default Copyright string is not appearing in store front

**Comment by treoden** [comment] 2023-10-15 10:16
Hi @dev-ST-IA ,

Can you share some screenshot of your configuration and the actual result on the web?

Thanks

**Comment by mark-jia** [comment] 2023-10-27 01:40
Hi @dev-ST-IA,
Is this issue resolved?

**Comment by mark-jia** [comment] 2023-10-27 05:34
This is a bug caused by defaultProps, the defaultProps when destructuring causing function calls when rendering and may cause a loop, suggest use default parameters instead. the defaultProps will be deprecated eventually.
Here is a reference link:
https://stackoverflow.com/questions/47774695/react-functional-component-default-props-vs-default-parameters
https://github.com/carbon-design-system/carbon/issues/10777(url)

**Comment by mark-jia** [comment] 2023-10-27 05:55
at the mean time, change 
<span>{copyRight}</span>
 to 
<span>{copyRight?copyRight:'© 2022 Evershop. All Rights Reserved.'}</span>
and delete Footer.defaultProps 
as an alternative

**Comment by dev-ST-IA** [comment] 2023-10-27 06:18
@treoden @mark-jia - this issue is something related to a typo. when you check the relevant graphql type that has the copyright property, it doesnt match the copyright prop specified in the default props and the props passed in to the Footer component.
either the prop needs to be changed from 'copyRight' to 'copyright' or the graphql property needs to be changed to 'copyRight'

**Comment by mark-jia** [comment] 2023-10-27 07:07
default.json in config directory can make it work
{
  "themeConfig": {
      "logo": {
            "alt": "You amazing shop logo",
            "src": "/logo.png",
            "width": 100,
            "height": 100
        },
        "headTags": {
            "links": [],
            "metas": [],
            "scripts": []
        },
        "copyRight": "© 2022 Evershop. All Rights Reserved."
    }
}
Yes, when copyright is copyRight, it works

However, there is Danabra from facebook said from react 18.3, there will be warnings about defaultProps, and
change to use default parameter will preferred.

**Comment by mark-jia** [comment] 2023-10-27 07:08
https://twitter.com/dan_abramov/status/1133878326358171650

**Comment by mark-jia** [comment] 2023-10-27 07:10
I think you can close this issue if you don't want to make changes to defaultProps

**Comment by mark-jia** [comment] 2023-10-27 07:23
I can see the query override the defaultProps with a null, so either change the config or just fix the type in bootstrap.js will fix it.  packages/evershop/src/modules/cms/bootstrap.js change copyright to copyRight.
My bad, the defaultProps is not the problem at the moment.

**Comment by treoden** [comment] 2023-12-26 02:50
Fixed. Closing

**Closed by treoden** 2023-12-26 02:50 UTC
